name: Run smoke test in Docker container
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: silkeh/clang:20
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1
        show-progress: false
    - run: |
        clang --version
        llvm-config --version
    - name: Install curl
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt install -y curl
    - name: Install Rust
      run: |
        curl -o rust-init.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
        sh ./rust-init.sh -y
    - run: |
        clang --version
        llvm-config --version
    - run: ./prerequisites.bash --no-sudo
    - run: ./build.bash
    - run: cd ./build && ctest
