name: Smoke test with LLVM 18
on: [push, pull_request]
env:
  LLVM_VERSION: 18
  SUDO: sudo
  NOSUDO:
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false
      - name: Remove old versions of clang and llvm
        run: |
          ./remove-all-llvm.bash $NOSUDO
      - name: Install curl
        run: |
          export DEBIAN_FRONTEND=noninteractive
          $SUDO apt update
          $SUDO apt install -y curl
      - name: Install Rust
        run: |
          curl -o rust-init.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
          sh ./rust-init.sh -y
      - run: ./prerequisites.bash $NOSUDO --latest --llvm-version=$LLVM_VERSION
      - run: ./build.bash
      - name: Run ctest
        run: |
          cd ./build
          ctest || ctest --rerun-failed --output-on-failure
      - name: Transpile LibmCS
        run: |
          pushd ../libmcs
          make clean
          bear -- make -j"$(nproc)"
          popd
          ./hayroll ../libmcs/compile_commands.json ./output/
      - name: Build Transpiled LibmCS
        run: |
          pushd ./output
          cargo build
          popd
